# MySQL 数据库相关配置
mysql:
  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  addr: 127.0.0.1:3306
  # MySQL 用户名(建议授权最小权限集)
  username: fastgo
  # MySQL 用户密码
  password: fastgo1234
  # fastgo 系统所用的数据库名
  database: fastgo
  # MySQL 最大空闲连接数，默认 100
  max-idle-connections: 100
  # MySQL 最大打开的连接数，默认 100
  max-open-connections: 100
  # 空闲连接最大存活时间，默认 10s
  max-connection-life-time: 10s
